export const ADD_LIST = "ADD_LIST"
export const DELETE_LIST = "DELETE_LIST"

export const ADD_CARD = "ADD_CARD"
export const UPDATE_LIST_ORDER = "UPDATE_LIST_ORDER"
export const UPDATE_CARDS_BETWEEN_LISTS = "UPDATE_CARDS_BETWEEN_LISTS"
