
GET http://localhost:5500/api/item 
Content-Type: application/json

###

POST http://localhost:5500/api/item 
Content-Type: application/json

{
"item": "my dear"
}

###

PUT http://localhost:5500/api/item/639836d77a6ef40fd5ac0624

Content-Type: application/json
{
    "item": "property 222 is updated"
}


###
DELETE  http://localhost:5500/api/item/6398375b7a6ef40fd5ac062e

Content-Type: application/json

###
GET http://localhost:5500/api/order 
Content-Type: application/json


###
POST http://localhost:5500/api/order
Content-Type: application/json

{
"order": ["list4", "list5"]
}

###
PUT http://localhost:5500/api/order/63988be98ab3f2970ee2bc26

Content-Type: application/json
{
"order": ["updated", "updatedddd"]
}




